/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-11-25 17:11:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Movie;

public final class Movies_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Movie");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");


	String userName= (String)session.getAttribute("userName");
	//int custID= (int)session.getAttribute("customerID");
	Movie rogers= (Movie)request.getAttribute("rogers");
	Movie angels= (Movie)request.getAttribute("angels");
	Movie doctor= (Movie)request.getAttribute("doctor");
	Movie ford= (Movie)request.getAttribute("ford");
	Movie frozen= (Movie)request.getAttribute("frozen");
	Movie joker= (Movie)request.getAttribute("joker");
	Movie last= (Movie)request.getAttribute("christmas");
	Movie midway= (Movie)request.getAttribute("midway");
	Movie playing= (Movie)request.getAttribute("playing");
	Movie liar= (Movie)request.getAttribute("liar");


      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<link href=\"./style/style.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<title>AMC Theaters: Movies</title>\n");
      out.write("<style>\n");
      out.write(".container {\n");
      out.write("  position: relative;\n");
      out.write("  width: 50%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(".overlay {\n");
      out.write("  position: absolute;\n");
      out.write("  bottom: 0;\n");
      out.write("  left: 0;\n");
      out.write("  right: 0;\n");
      out.write("  background-color: #008CBA;\n");
      out.write("  overflow: hidden;\n");
      out.write("  width: 120%;\n");
      out.write("  height: 100%;\n");
      out.write("  -webkit-transform: scale(0);\n");
      out.write("  -ms-transform: scale(0);\n");
      out.write("  transform: scale(0);\n");
      out.write("  -webkit-transition: .3s ease;\n");
      out.write("  transition: .3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container:hover .overlay {\n");
      out.write("  -webkit-transform: scale(1);\n");
      out.write("  -ms-transform: scale(1);\n");
      out.write("  transform: scale(1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".text {\n");
      out.write("  color: white;\n");
      out.write("  font-size: 20px;\n");
      out.write("  position: absolute;\n");
      out.write("  top: 50%;\n");
      out.write("  left: 50%;\n");
      out.write("  -webkit-transform: translate(-50%, -50%);\n");
      out.write("  -ms-transform: translate(-50%, -50%);\n");
      out.write("  transform: translate(-50%, -50%);\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<h1><center>AMC Theaters</center></h1>\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("\n");
      out.write("<nav>\n");
      out.write("<ul>\n");
      out.write("<li><a href=\"MovieServlet\">Movies</a></li>\n");
      out.write("<li id=\"username\">Welcome ");
      out.print( userName );
      out.write("!</li>\n");
      out.write("<li><a href=\"ReadCartServlet\" id=\"cartLogo\"><img src=\"images/cart2.png\" alt=\"\" id=\"cartLogo\"/></a></li>\n");
      out.write("</ul>\n");
      out.write("</nav>\n");
      out.write("</header>\n");
      out.write("<br>\n");
      out.write("<h2>Featured Movies</h2>\n");
      out.write(" \n");
      out.write("<table width=\"100%\" border=\"0\">\n");
      out.write("  <tr> \n");
      out.write(" <div class=\"container\">  \n");
      out.write(" \t<td><img src=\"images/frozen.jpeg\" alt=\"\"/><br><label>");
      out.print(frozen.getMovieName());
      out.write(" <br> ");
      out.print( frozen.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(frozen.getRating() );
      out.write("<br>Released ");
      out.print(frozen.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write("\t\n");
      out.write("\t<td><img src=\"images/angels.jpg\" alt=\"\"/><br><label>");
      out.print(angels.getMovieName());
      out.write(" <br> ");
      out.print( angels.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(angels.getRating() );
      out.write("<br>Released ");
      out.print(angels.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write("\t\n");
      out.write("\t<td><img src=\"images/ford.jpg\" alt=\"\"/><br><label>");
      out.print(ford.getMovieName());
      out.write(" <br> ");
      out.print( ford.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(ford.getRating() );
      out.write("<br>Released ");
      out.print(ford.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write("\t\n");
      out.write("\t<td><img src=\"images/christmas.jpg\" alt=\"\"/><br><label>");
      out.print(last.getMovieName());
      out.write(" <br> ");
      out.print( last.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(last.getRating() );
      out.write("<br>Released ");
      out.print(last.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write("\t\n");
      out.write("\t<td><img src=\"images/tomHanks.jpeg\" alt=\"\" /><br><label>");
      out.print(rogers.getMovieName());
      out.write(" <br> ");
      out.print( rogers.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(rogers.getRating() );
      out.write("<br>Released ");
      out.print(rogers.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write(" </div>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("<br><br>\n");
      out.write("<p>----------------------------------------------------------------------------------------------------------------</p>\n");
      out.write("<br><br>\n");
      out.write("<table width=\"100%\" border=\"0\">\n");
      out.write("  <tr> \n");
      out.write(" <div class=\"container\">  \n");
      out.write("  \t<td><img src=\"images/midway.jpg\" alt=\"\"/><br><label>");
      out.print(midway.getMovieName());
      out.write(" <br> ");
      out.print( midway.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(midway.getRating() );
      out.write("<br>Released ");
      out.print(midway.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write("\t\n");
      out.write("\t<td><img src=\"images/joker.jpg\" alt=\"\"/><br><label>");
      out.print(joker.getMovieName());
      out.write(" <br> ");
      out.print( joker.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(joker.getRating() );
      out.write("<br>Released ");
      out.print(joker.getReleaseDate() );
      out.write("</label></td>\n");
      out.write("\t\t\n");
      out.write("\t<td><img src=\"images/liar.jpg\" alt=\"\"/><br><label>");
      out.print(liar.getMovieName());
      out.write(" <br> ");
      out.print( liar.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(liar.getRating() );
      out.write("<br>Released ");
      out.print(liar.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write("\t\n");
      out.write("\t<td><img src=\"images/fire.jpg\" alt=\"\"/><br><label>");
      out.print(playing.getMovieName());
      out.write(" <br> ");
      out.print( playing.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(playing.getRating() );
      out.write("<br>Released ");
      out.print(playing.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write("\t\n");
      out.write("\t<td><img src=\"images/doctor.png\" alt=\"\" /><br><label>");
      out.print(doctor.getMovieName());
      out.write(" <br> ");
      out.print( doctor.getRunningTime() );
      out.write(" |\n");
      out.write("\t");
      out.print(doctor.getRating() );
      out.write("<br>Released ");
      out.print(doctor.getReleaseDate() );
      out.write("</label></td>\t\n");
      out.write(" </div>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("<form action=\"Ticket.jsp\" >\n");
      out.write("<input type=\"submit\" name=\"submit\" value=\"Get Tickets\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
