/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-11-25 17:11:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Ticket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write(" ");

	String userName= (String)session.getAttribute("userName");

 
      out.write("   \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<link href=\"./style/style.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<title>Purchase Tickets</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1><center>AMC Theaters</center></h1>\n");
      out.write("<header>\n");
      out.write("<nav>\n");
      out.write("<ul>\n");
      out.write("<li><a href=\"MovieServlet\">Movies</a></li>\n");
      out.write("<li><a href=\"ReadCartServlet\" id=\"cartLogo\"><img src=\"images/cart2.png\" alt=\"\" id=\"cartLogo\"/></a></li>\n");
      out.write("</ul>\n");
      out.write("</nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("<h2>Get Your Tickets</h2>\n");
      out.write("\n");
      out.write("<form name=\"purchaseForm\" action=\"CreateCartServlet\" method=\"post\">\n");
      out.write("\n");
      out.write("<h3>Select A Movie:</h3>\n");
      out.write("<select name=\"movies\">\n");
      out.write("<option value=\"A Beautiful Day in The Neighborhood\">A Beautiful Day in The Neighborhood</option>\n");
      out.write("<option value=\"Charlie's Angels\">Charlie's Angels</option>\n");
      out.write("<option value=\"Doctor Sleep\">Doctor Sleep</option>\n");
      out.write("<option value=\"Ford v Ferrari\">Ford v Ferrari</option>\n");
      out.write("<option value=\"Frozen II\">Frozen II</option>\n");
      out.write("<option value=\"Joker\">Joker</option>\n");
      out.write("<option value=\"Last Christmas\">Last Christmas</option>\n");
      out.write("<option value=\"Midway\">Midway</option>\n");
      out.write("<option value=\"Playing With Fire\">Playing with Fire</option>\n");
      out.write("<option value=\"The Good Liar\">The Good Liar</option>\n");
      out.write("</select>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("<h3>Select A Date:</h3>\n");
      out.write("<input type=\"date\" name=\"date\"  value=\"\">\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("<h3>Time:</h3>\n");
      out.write("<label>5:15p.m</label>\n");
      out.write("<input type=\"radio\" name=\"times\" value=\"5:15\"/>\n");
      out.write("\n");
      out.write("<label>7:00p.m</label>\n");
      out.write("<input type=\"radio\" name=\"times\" value=\"7:00\"/>\n");
      out.write("\n");
      out.write("<label>8:30p.m</label>\n");
      out.write("<input type=\"radio\" name=\"times\" value=\"8:30\"/>\n");
      out.write("\n");
      out.write("<label>9:15p.m</label>\n");
      out.write("<input type=\"radio\" name=\"times\" value=\"9:15\"/>\n");
      out.write("<br>\n");
      out.write("<label>10:55p.m</label>\n");
      out.write("<input type=\"radio\" name=\"times\" value=\"10:55\"/>\n");
      out.write("\n");
      out.write("<label>11:00p.m</label>\n");
      out.write("<input type=\"radio\" name=\"times\" value=\"11:00\"/>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("<h3>Select a Ticket Type:</h3>\n");
      out.write("\n");
      out.write("<label>Adult- Ages: 18+ </label><br>\n");
      out.write("<label>$7.99 </label><br>\n");
      out.write("<input type=\"number\" name=\"adult\" min=\"0\" max=\"15\" value=\"0\">\n");
      out.write("<br>\n");
      out.write("<label>Child- Ages: 2-17 </label><br>\n");
      out.write("<label>$5.99 </label><br>\n");
      out.write("<input type=\"number\" name=\"child\" min=\"0\" max=\"15\" value=\"0\">\n");
      out.write("<br><br>\n");
      out.write("<input type=\"submit\" name=\"submit\" value=\"Continue\"/>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
